### ISSUE TITLE
Fatal Error: Class 'GearmanClient' not found

### ISSUE THREAD

**Issue by erighetto** [ulabox/GearmanBundle#6]
After upgrading to Symfony 2.8 I can't get this bundle working anymore.

When on CLI I write php app/console gearman:worker:execute --worker=AthenaDapiBundle:DapiWorker

I get this error:

``` javascript
  [Symfony\Component\Debug\Exception\ClassNotFoundException]
  Attempted to load class "GearmanClient" from the global namespace.
  Did you forget a "use" statement for "Ulabox\Bundle\GearmanBundle\Gearman\Client\GearmanClient"?
```

I thought the problem was the php version running on server (5.4) so i upgraded it to 5.6 but I wasn't luck: the error is still there.

Any suggestion on how debug and fix?

![cattura](https://cloud.githubusercontent.com/assets/3954972/12120276/6e6f4df0-b3d0-11e5-8995-fcae3d633ff6.JPG)

**Comment by erighetto** [comment]
Sorry for the useless noise guys! After hours of debug I'm pretty sure that is not a issue related to this bundle but the problem is the build of php and its gearman driver.

**Comment by nnset** [comment]
No problem @erighetto , just keep us posted in case you find something weird.
Regards!
